services:
  db:
    image: postgres
    container_name: GoKapture_db    \
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
